# Generated by Django 3.1.5 on 2021-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('y_coordinate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('name', models.CharField(default='India', max_length=30)),
                ('store', models.BooleanField()),
                ('warehouse', models.BooleanField()),
            ],
        ),
    ]
